; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "InterfaceSapSiemensMuc"
#define MyAppVersion "1.0.0"
#define MyAppApiVersion "15.2.7"
#define MyAppPublisher "proadvise GmbH"
#define MyAppURL "http://www.proadvise.com/"
#define InnoDir ".\"
#define Today GetDateTimeString('yyyymmdd', '', '')
#define ActualYear GetDateTimeString('yyyy', '', '')

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AlwaysShowDirOnReadyPage=true
AlwaysShowGroupOnReadyPage=true
AppCopyright=Copyright � {#ActualYear} {#MyAppPublisher}
AppID={#MyAppName}_{#MyAppApiVersion}
AppName={#MyAppName}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
AppVerName={#MyAppName} {#MyAppVersion}
AppVersion={#MyAppVersion}
ArchitecturesInstallIn64BitMode=x64 ia64
Compression=lzma/Max
DefaultDirName={pf}\proadvise\{#MyAppName}
DefaultGroupName=proadvise\{#MyAppName}
DirExistsWarning=auto
DisableProgramGroupPage=yes
EnableDirDoesntExistWarning=true
InfoAfterFile={#InnoDir}\postinstallinfo.txt
LicenseFile={#InnoDir}\license.txt
MinVersion=,5.1.2600sp1
OutputBaseFilename=setup-{#MyAppName}-p6_{#MyAppApiVersion}-{#MyAppVersion}
OutputDir=..\..\target
SetupIconFile={#InnoDir}\pa_favicon.ico
ShowComponentSizes=false
ShowLanguageDialog=no
SolidCompression=true
UninstallFilesDir={app}\Uninstall
VersionInfoCompany={#MyAppPublisher}
VersionInfoCopyright={#ActualYear} (C) {#MyAppPublisher}
VersionInfoProductName={#MyAppName}
VersionInfoProductVersion={#MyAppVersion}
VersionInfoVersion={#MyAppVersion}
WizardImageFile={#InnoDir}\pa_logo_168.BMP
WizardSmallImageFile={#InnoDir}\pa_favicon.BMP
FlatComponentsList=false
UsePreviousSetupType=false
SetupLogging=true

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"

[Files]
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
Source: "..\workdir\*";Excludes: "*\application.properties,*\log4j.properties,*\on-failed-template.txt,*\on-success-template.txt"; DestDir: {app}; Flags: ignoreversion recursesubdirs; 
Source: "..\workdir\config\application.properties"; DestDir: {app}\config; Flags:onlyifdoesntexist ;
Source: "..\workdir\config\log4j.properties"; DestDir: {app}\config; Flags:onlyifdoesntexist ;
Source: "..\workdir\config\mail\on-failed-template.txt"; DestDir: {app}\config\mail; Flags:onlyifdoesntexist ;
Source: "..\workdir\config\mail\on-success-template.txt"; DestDir: {app}\config\mail; Flags:onlyifdoesntexist ;

[Icons]
Name: "{group}\{cm:ProgramOnTheWeb,{#MyAppName}}"; Filename: "{#MyAppURL}"
Name: "{group}\{#MyAppName} Benutzerhandbuch"; Filename: {app}\Docu\{#MyAppName}_Benutzerhandbuch.pdf; 

[Run]

[Ini]

[UninstallDelete]
Name: {app}\*; Type: filesandordirs;
Name: {app}\*; Type: dirifempty;
Name: {app}; Type: dirifempty;


[Dirs]
;Name: {app}\resources; Components: {#ComponentAll};

[Types]
;Name: "full";    Description: "Vollinstallation"
;Name: "compact"; Description: "Minimal"
Name: "custom";  Description: "Benutzerdefiniert"; Flags: iscustom

[Code]
procedure CurStepChanged(CurStep: TSetupStep);
var
 logfilepathname, logfilename, newfilepathname: string;

 begin
    logfilepathname := expandconstant('{log}');
    logfilename := ExtractFileName(logfilepathname);
    newfilepathname := expandconstant('{app}\') +logfilename;

if CurStep = ssDone then
 begin
     filecopy(logfilepathname, newfilepathname, false);
    end;

end; 
